/**
 * Pine Genie Signature Templates
 * 
 * Default signature templates for different types of code generation.
 * These templates include professional branding and attribution information.
 */

import {
  SignatureTemplate,
  SignatureDefaults,
  SignatureType,
  SignaturePosition
} from '../../types/signature';

/**
 * Default signature templates for each generation type
 */
export const DEFAULT_TEMPLATES: Record<SignatureType, SignatureTemplate> = {
  [SignatureType.TEMPLATE]: {
    id: 'template-default',
    name: 'Template Generated Script',
    type: SignatureType.TEMPLATE,
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Professional Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie Template System
// Template: {{templateName}}
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// Website: https://pinegenie.com
// 
// ⚡ Powered by Pine Genie - The Ultimate Pine Script Generator
// 📈 Create professional trading strategies with zero coding experience
// 
// ═══════════════════════════════════════════════════════════════════════════════`,
    variables: [
      { name: 'templateName', type: 'string', required: true },
      { name: 'strategyName', type: 'string', required: true },
      { name: 'timestamp', type: 'datetime', required: true },
      { name: 'version', type: 'string', required: true }
    ],
    position: SignaturePosition.TOP,
    enabled: true
  },

  [SignatureType.BUILDER]: {
    id: 'builder-default',
    name: 'Visual Builder Generated Script',
    type: SignatureType.BUILDER,
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Visual Strategy Builder
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie Visual Builder
// Strategy: {{strategyName}}
// Nodes: {{nodeCount}}
// Generated: {{timestamp}}
// Version: {{version}}
// Website: https://pinegenie.com
// 
// 🎨 Built with Pine Genie's drag-and-drop visual builder
// 🚀 No coding required - Professional results guaranteed
// 
// ═══════════════════════════════════════════════════════════════════════════════`,
    variables: [
      { name: 'strategyName', type: 'string', required: true },
      { name: 'nodeCount', type: 'number', required: false },
      { name: 'timestamp', type: 'datetime', required: true },
      { name: 'version', type: 'string', required: true }
    ],
    position: SignaturePosition.TOP,
    enabled: true
  },

  [SignatureType.AI_CHAT]: {
    id: 'ai-chat-default',
    name: 'AI Generated Script',
    type: SignatureType.AI_CHAT,
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - AI-Powered Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie AI Assistant
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// Website: https://pinegenie.com
// 
// 🤖 Created with Pine Genie's advanced AI technology
// 💬 From natural language to professional Pine Script
// 
// ═══════════════════════════════════════════════════════════════════════════════`,
    variables: [
      { name: 'strategyName', type: 'string', required: true },
      { name: 'timestamp', type: 'datetime', required: true },
      { name: 'version', type: 'string', required: true }
    ],
    position: SignaturePosition.TOP,
    enabled: true
  },

  [SignatureType.CUSTOM]: {
    id: 'custom-default',
    name: 'Custom Generated Script',
    type: SignatureType.CUSTOM,
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Professional Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// Website: https://pinegenie.com
// 
// 🚀 Powered by Pine Genie - Professional Trading Strategy Generator
// 
// ═══════════════════════════════════════════════════════════════════════════════`,
    variables: [
      { name: 'strategyName', type: 'string', required: true },
      { name: 'timestamp', type: 'datetime', required: true },
      { name: 'version', type: 'string', required: true }
    ],
    position: SignaturePosition.TOP,
    enabled: true
  }
};

/**
 * System default configuration for signatures
 */
export const DEFAULT_SIGNATURE_DEFAULTS: SignatureDefaults = {
  enabled: true,
  defaultType: SignatureType.TEMPLATE,
  defaultPosition: SignaturePosition.TOP,
  defaultVerbosity: 'standard',
  brandingText: 'Pine Genie - Professional Pine Script Generator',
  websiteUrl: 'https://pinegenie.com',
  version: '1.0'
};

/**
 * Minimal signature templates for different verbosity levels
 */
export const MINIMAL_TEMPLATES: Record<SignatureType, string> = {
  [SignatureType.TEMPLATE]: '// Generated by Pine Genie Template System - {{timestamp}}',
  [SignatureType.BUILDER]: '// Generated by Pine Genie Visual Builder - {{timestamp}}',
  [SignatureType.AI_CHAT]: '// Generated by Pine Genie AI Assistant - {{timestamp}}',
  [SignatureType.CUSTOM]: '// Generated by Pine Genie - {{timestamp}}'
};

/**
 * Detailed signature templates for verbose output
 */
export const DETAILED_TEMPLATES: Record<SignatureType, SignatureTemplate> = {
  [SignatureType.TEMPLATE]: {
    ...DEFAULT_TEMPLATES[SignatureType.TEMPLATE],
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Professional Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie Template System
// Template: {{templateName}}
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// User: {{userId}}
// Website: https://pinegenie.com
// 
// ⚡ Powered by Pine Genie - The Ultimate Pine Script Generator
// 📈 Create professional trading strategies with zero coding experience
// 🎯 Template-based generation for consistent, reliable results
// 
// Generation Details:
// - Type: Template-based generation
// - Timestamp: {{timestamp}}
// - Version: {{version}}
// 
// ═══════════════════════════════════════════════════════════════════════════════`
  },

  [SignatureType.BUILDER]: {
    ...DEFAULT_TEMPLATES[SignatureType.BUILDER],
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Visual Strategy Builder
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie Visual Builder
// Strategy: {{strategyName}}
// Nodes: {{nodeCount}}
// Generated: {{timestamp}}
// Version: {{version}}
// User: {{userId}}
// Website: https://pinegenie.com
// 
// 🎨 Built with Pine Genie's drag-and-drop visual builder
// 🚀 No coding required - Professional results guaranteed
// 🔧 Visual node-based strategy construction
// 
// Builder Details:
// - Node Count: {{nodeCount}}
// - Generation Type: Visual Builder
// - Timestamp: {{timestamp}}
// - Version: {{version}}
// 
// ═══════════════════════════════════════════════════════════════════════════════`
  },

  [SignatureType.AI_CHAT]: {
    ...DEFAULT_TEMPLATES[SignatureType.AI_CHAT],
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - AI-Powered Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie AI Assistant
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// User: {{userId}}
// Website: https://pinegenie.com
// 
// 🤖 Created with Pine Genie's advanced AI technology
// 💬 From natural language to professional Pine Script
// 🧠 Intelligent code generation with context awareness
// 
// AI Generation Details:
// - Type: AI-powered generation
// - Timestamp: {{timestamp}}
// - Version: {{version}}
// 
// ═══════════════════════════════════════════════════════════════════════════════`
  },

  [SignatureType.CUSTOM]: {
    ...DEFAULT_TEMPLATES[SignatureType.CUSTOM],
    template: `// ═══════════════════════════════════════════════════════════════════════════════
// 🌲 Pine Genie - Professional Pine Script Generator
// ═══════════════════════════════════════════════════════════════════════════════
// 
// Generated by: Pine Genie
// Strategy: {{strategyName}}
// Generated: {{timestamp}}
// Version: {{version}}
// User: {{userId}}
// Website: https://pinegenie.com
// 
// 🚀 Powered by Pine Genie - Professional Trading Strategy Generator
// 📊 Custom generation with advanced features
// 
// Generation Details:
// - Type: Custom generation
// - Timestamp: {{timestamp}}
// - Version: {{version}}
// 
// ═══════════════════════════════════════════════════════════════════════════════`
  }
};